# Generated by Django 5.1.4 on 2026-07-21 21:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_seen', models.DateTimeField(db_index=True)),
                ('first_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('pageview_count', models.PositiveIntegerField(default=0)),
                ('session_count', models.PositiveIntegerField(default=1)),
                ('is_known_bot', models.BooleanField(db_index=True, default=False)),
                ('max_risk_score', models.PositiveSmallIntegerField(default=0)),
                ('last_user_agent', models.TextField(blank=True)),
                ('last_country', models.CharField(blank=True, db_index=True, max_length=2)),
                ('last_city', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ('-last_seen',),
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(db_index=True, max_length=1000)),
                ('status_code', models.PositiveSmallIntegerField(db_index=True)),
                ('response_ms', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, db_index=True, max_length=20)),
                ('browser', models.CharField(blank=True, max_length=40)),
                ('is_bot', models.BooleanField(db_index=True, default=False)),
                ('bot_reason', models.CharField(blank=True, max_length=255)),
                ('risk_score', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('requests_per_minute', models.PositiveIntegerField(default=1)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pageviews', to='analytics.visitor')),
            ],
            options={
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(choices=[('rate_spike', 'Traffic spike'), ('scanner', 'Vulnerability scan'), ('automation', 'Suspicious automation'), ('bad_request', 'Suspicious request')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('path', models.CharField(blank=True, max_length=1000)),
                ('summary', models.CharField(max_length=255)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('pageview', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_event', to='analytics.pageview')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_security_events', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to='analytics.visitor')),
            ],
            options={
                'ordering': ('-occurred_at',),
                'indexes': [models.Index(fields=['resolved', 'severity', 'occurred_at'], name='analytics_s_resolve_09ee4d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['occurred_at', 'is_bot'], name='analytics_p_occurre_846784_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['occurred_at', 'risk_score'], name='analytics_p_occurre_d1923c_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['ip_address', 'occurred_at'], name='analytics_p_ip_addr_17177a_idx'),
        ),
    ]
