"""
Django settings for _core project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()  # take environment variables from .env.

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    '192.168.2.116',
    'localhost',
    'ineedtohirethisguy.com',
    'www.ineedtohirethisguy.com',
    '127.0.0.1',
    '192.168.2.199',
]

# Add domain to the list of trusted origins so that Django accepts requests from that domain
CSRF_TRUSTED_ORIGINS = [
    'https://ineedtohirethisguy.com',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Program's apps:
    'main',
    'blog',
    'analytics',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Records public traffic after authentication is available, so staff and
    # the private dashboard can be excluded safely.
    'analytics.middleware.VisitTrackingMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Authentication for /admin/ and the private Trace dashboard must never travel
# over plaintext in production. Keep local HTTP development convenient.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SECURE_CONTENT_TYPE_NOSNIFF = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

# STATIC SETTINGS FOR WHITENOISE
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    # Put strings here, like "/home/html/static" or "C:/www/django/static".
    # Always use forward slashes, even on Windows.
    # Don't forget to use absolute paths, not relative paths.
    BASE_DIR / "static",
]

STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
)

# WhiteNoise fingerprints and compresses every asset in all environments.
# The fingerprint changes whenever the file changes, so browsers never keep
# serving an obsolete CSS file after a deployment.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# SMPT GMAIL
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = int(os.getenv("EMAIL_PORT"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", True)
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")


# > For development purposes no further configuration is required. By default, django-Turnstile will use dummy keys.
# > For production, you’ll need to obtain your Turnstile site key and secret key and add them to you settings:
TURNSTILE_SITEKEY = os.getenv("TURNSTILE_SITEKEY")
TURNSTILE_SECRET = os.getenv("TURNSTILE_SECRET")

# If you need to, you can also override default turnstile endpoints:
TURNSTILE_JS_API_URL = 'https://challenges.cloudflare.com/turnstile/v0/api.js'
TURNSTILE_VERIFY_URL = 'https://challenges.cloudflare.com/turnstile/v0/siteverify'

# Change default verification timeout:
TURNSTILE_TIMEOUT = 5


# Private, first-party traffic analytics. Proxy headers are only accepted from
# these addresses/networks to prevent visitors spoofing their IP or location.
ANALYTICS_ENABLED = os.getenv('ANALYTICS_ENABLED', 'True') == 'True'
ANALYTICS_RETENTION_DAYS = int(os.getenv('ANALYTICS_RETENTION_DAYS', '90'))
ANALYTICS_RATE_LIMIT_PER_MINUTE = int(
    os.getenv('ANALYTICS_RATE_LIMIT_PER_MINUTE', '60')
)
# Once an IP exceeds this multiple of the rate threshold, only one in every ten
# requests is persisted. The peak remains visible without letting an attack
# amplify database writes indefinitely.
ANALYTICS_ATTACK_SAMPLE_MULTIPLIER = int(
    os.getenv('ANALYTICS_ATTACK_SAMPLE_MULTIPLIER', '3')
)
ANALYTICS_TRUSTED_PROXIES = [
    item.strip()
    for item in os.getenv(
        'ANALYTICS_TRUSTED_PROXIES',
        # 192.168.2.104 is the verified origin proxy for this deployment.
        '127.0.0.1,::1,192.168.2.104',
    ).split(',')
    if item.strip()
]
ANALYTICS_EXCLUDED_PATHS = (
    '/admin/',
    '/ops/trace/',
    '/static/',
    '/media/',
    '/favicon.ico',
)

# Gunicorn runs multiple workers. A shared Redis cache makes rate and alert
# deduplication counters consistent across every worker. Analytics handles a
# cache outage gracefully, so Redis can never take down the public site.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'portfolio-default',
    },
    'analytics': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.getenv(
            'ANALYTICS_REDIS_URL', 'redis://127.0.0.1:6379/2'
        ),
        'OPTIONS': {
            'socket_connect_timeout': 1,
            'socket_timeout': 1,
        },
        'KEY_PREFIX': 'trace',
    },
}
