# Generated by Django 5.1.4 on 2025-01-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'created_on', 'ordering': ['-created_on'], 'verbose_name_plural': 'posts'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=888, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=777, unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('title', 'slug')},
        ),
    ]
